# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - dotnet tool restore
      - dotnet cake --target=Build
      - dotnet cake --target=Test
      - dotnet cake --target=Pack
    silent: true
