# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - dotnet tool restore
      - dotnet format whitespace --verbosity diagnostic
      - dotnet format style --severity info --verbosity diagnostic
      - dotnet format analyzers --severity info --verbosity diagnostic
      - dotnet cake --target=Build
      - dotnet cake --target=Test
      - dotnet cake --target=Pack
    silent: true
